const Arrays = {
    searchArray: [
        'meme',
        'star-wars',
        'funny',
        'animal',
        'random',
        'anime',
        'cli',
        'metal',
        'npm',
        'language',
        'light',
		'dark',
		'spring',
		'summer',
		'autumn',
		'winter',
		'bronze',
		'angelic',
		'lawless',
		'enchanted',
		'regal',
		'crystal',
		'locked',
		'secret',
		'entwined',
		'medieval',
		'crescent',
		'falling',
		'flying',
		'dreaming',
		'toxic',
		'guardian',
		'chiming',
		'stormy',
		'lightning',
		'flaming',
		'earth',
		'misty',
		'windy',
		'shadow',
		'amethyst',
		'jade',
		'emerald',
		'sapphire',
		'aquamarine',
		'oriental',
		'cloudy',
		'ragged',
		'masked',
		'platinum',
		'honourable',
		'power',
		'mountain',
		'rocky',
		'miniature',
		'elven',
		'clocks',
		'fairies',
		'flowers',
		'roses',
		'lanterns',
		'books',
		'library',
		'spirit',
		'wood',
		'tears',
		'charm',
		'petals',
		'snow',
		'bottle',
		'vines',
		'key',
		'portal',
		'bottle',
		'butterflies',
		'dragonflies',
		'spiders',
		'moon',
		'sun',
		'stars',
		'ruin',
		'pendant',
		'bones',
		'lace',
		'fish',
		'bubbles',
		'statue',
		'dew',
		'odyssey',
		'elves',
		'love',
		'faith',
		'hope',
		'wisps',
		'innocent',
		'rainbow',
		'treasure',
		'pirate',
		'illusion',
		'danger',
		'magic',
		'melody',
		'hero',
		'words',
		'mirror',
		'solitude',
		'identical',
		'visual',
		'historical',
		'elemental',
		'dragon',
		'valuable',
		'revolutionary',
		'colourful',
		'isolated',
		'passionate',
		'governor',
		'musical',
		'whimsical',
		'rigid',
		'flowing',
		'chamber',
		'keeper',
		'identity',
		'shy',
		'mechanical',
		'transforming',
		'destiny',
		'curious',
		'cogs',
		'gemstones',
		'leaves',
		'pure',
		'crowning',
		'potion',
		'thistled',
		'glass',
		'fragile',
		'comet',
		'shattered',
		'books',
		'ocean',
		'diadem',
		'glowing',
		'message',
		'bouquet',
		'shells',
		'crisis',
		'fantasy',
		'note',
		'puzzled',
		'mystery',
		'fern',
		'glimmer',
		'pillars',
		'captain',
		'framed',
		'rusted',
		'harmonic'
    ],
    apiArray: [
        {
            name: 'NASA',
            locationUrl: 'https://api.nasa.gov/'
        },
        {
            name: 'Hubble',
            locationUrl: 'http://hubblesite.org/api/documentation'
        },
        {
            name: 'Freesound',
            locationUrl: 'https://freesound.org/help/developers/'
        },
        {
            name: 'Fun translations',
            locationUrl: 'https://funtranslations.com/api'
        },
        {
            name: 'jService',
            locationUrl: 'https://jservice.io'
        },
        {
            name: 'COULORlovers',
            locationUrl: 'https://www.colourlovers.com/api'
        },
        {
            name: 'spoonacular recipe and food',
            locationUrl: 'https://spoonacular.com/food-api'
        },
        {
            name: 'imgur',
            locationUrl: 'https://apidocs.imgur.com'
        },
        {
            name: 'Deck of Cards',
            locationUrl: 'https://www.deckofcardsapi.com'
        },
        {
            name: 'PokeApi',
            locationUrl: 'https://pokeapi.co'
        }
    ],
    frameworkArray: [
        {
            name: 'Pure',
            locationUrl: 'https://purecss.io',
            description: ''
        },
        {
            name: 'Bulma',
            locationUrl: 'https://bulma.io/'
        }, 
        {
            name: 'NES',
            locationUrl: 'https://nostalgic-css.github.io/NES.css/'
        }, 
        {
            name: 'Semantic UI',
            locationUrl: 'https://semantic-ui.com/'
        }, 
        {
            name: 'Skeleton',
            locationUrl: 'http://getskeleton.com/'
        }, 
        {
            name: 'Materialize',
            locationUrl: 'https://materializecss.com/'
        }, 
        {
            name: 'Milligram',
            locationUrl: 'https://milligram.io/'
        }, 
        {
            name: 'Tailwind',
            locationUrl: 'https://tailwindcss.com/'
        },

    ]
}
export default Arrays