const Arrays = {
    searchArray: [
        'meme',
        'star-wars',
        'funny',
        'animal',
        'random',
        'anime',
        'cli',
        'metal',
        'npm',
        'language',
        'Light',
		'Dark',
		'Spring',
		'Summer',
		'Autumn',
		'Winter',
		'Bronze',
		'Angelic',
		'Lawless',
		'Enchanted',
		'Regal',
		'Crystal',
		'Locked',
		'Secret',
		'Entwined',
		'Medieval',
		'Crescent',
		'Falling',
		'Flying',
		'Dreaming',
		'Toxic',
		'Guardian',
		'Chiming',
		'Stormy',
		'Lightning',
		'Flaming',
		'Earth',
		'Misty',
		'Windy',
		'Shadow',
		'Amethyst',
		'Jade',
		'Emerald',
		'Sapphire',
		'Aquamarine',
		'Oriental',
		'Cloudy',
		'Ragged',
		'Masked',
		'Platinum',
		'Honourable',
		'Power',
		'Mountain',
		'Rocky',
		'Miniature',
		'Elven',
		'Clocks',
		'Fairies',
		'Flowers',
		'Roses',
		'Lanterns',
		'Books',
		'Library',
		'Spirit',
		'Wood',
		'Tears',
		'Charm',
		'Petals',
		'Snow',
		'Bottle',
		'Vines',
		'Key',
		'Portal',
		'Bottle',
		'Butterflies',
		'Dragonflies',
		'Spiders',
		'Moon',
		'Sun',
		'Stars',
		'Ruin',
		'Pendant',
		'Bones',
		'Lace',
		'Fish',
		'Bubbles',
		'Statue',
		'Dew',
		'Odyssey',
		'Elves',
		'Love',
		'Faith',
		'Hope',
		'Wisps',
		'Innocent',
		'Rainbow',
		'Treasure',
		'Pirate',
		'Illusion',
		'Danger',
		'Magic',
		'Melody',
		'Hero',
		'Words',
		'Mirror',
		'Solitude',
		'Identical',
		'Visual',
		'Historical',
		'Elemental',
		'Dragon',
		'Valuable',
		'Revolutionary',
		'Colourful',
		'Isolated',
		'Passionate',
		'Governor',
		'Musical',
		'Whimsical',
		'Rigid',
		'Flowing',
		'Chamber',
		'Keeper',
		'Identity',
		'Shy',
		'Mechanical',
		'Transforming',
		'Destiny',
		'Curious',
		'Cogs',
		'Gemstones',
		'Leaves',
		'Pure',
		'Crowning',
		'Potion',
		'Thistled',
		'Glass',
		'Fragile',
		'Comet',
		'Shattered',
		'Books',
		'Ocean',
		'Diadem',
		'Glowing',
		'Message',
		'Bouquet',
		'Shells',
		'Crisis',
		'Fantasy',
		'Note',
		'Puzzled',
		'Mystery',
		'Fern',
		'Glimmer',
		'Pillars',
		'Captain',
		'Framed',
		'Rusted',
		'Harmonic'
    ],
    apiArray: [
        {
            name: 'NASA',
            locationUrl: 'https://api.nasa.gov/'
        },
        {
            name: 'Hubble',
            locationUrl: 'http://hubblesite.org/api/documentation'
        },
        {
            name: 'Freesound',
            locationUrl: 'https://freesound.org/help/developers/'
        },
        {
            name: 'Fun translations',
            locationUrl: 'https://funtranslations.com/api'
        },
        {
            name: 'jService',
            locationUrl: 'https://jservice.io'
        },
        {
            name: 'COULORlovers',
            locationUrl: 'https://www.colourlovers.com/api'
        },
        {
            name: 'spoonacular recipe and food',
            locationUrl: 'https://spoonacular.com/food-api'
        },
        {
            name: 'imgur',
            locationUrl: 'https://apidocs.imgur.com'
        },
        {
            name: 'Deck of Cards',
            locationUrl: 'https://www.deckofcardsapi.com'
        },
        {
            name: 'PokeApi',
            locationUrl: 'https://pokeapi.co'
        }
    ],
    frameworkArray: [
        {
            name: 'Pure',
            locationUrl: 'https://purecss.io',
            description: ''
        },
        {
            name: 'Bulma',
            locationUrl: 'https://bulma.io/'
        }, 
        {
            name: 'NES',
            locationUrl: 'https://nostalgic-css.github.io/NES.css/'
        }, 
        {
            name: 'Semantic UI',
            locationUrl: 'https://semantic-ui.com/'
        }, 
        {
            name: 'Skeleton',
            locationUrl: 'http://getskeleton.com/'
        }, 
        {
            name: 'Materialize',
            locationUrl: 'https://materializecss.com/'
        }, 
        {
            name: 'Milligram',
            locationUrl: 'https://milligram.io/'
        }, 
        {
            name: 'Tailwind',
            locationUrl: 'https://tailwindcss.com/'
        },

    ]
}
export default Arrays